### ISSUE TITLE
add voila as another command

### ISSUE THREAD

**Issue by 1kastner** [hyperspy/start_jupyter_cm#26]
Is it easy and feasible to add voila as another command? Would a corresponding pull request be accepted or is it considered out of scope for this project?

**Comment by francisco-dlp** [comment]
It depends on what you plan to support. ``start_jupyter_cm`` adds a context menu items to start a jupyter-* in a folder. Adding an new item to start voila instead to serve notebooks in a given directory should be easy to implement and a PR would be more than welcome. However, selecting a file (notebook) and opening it with voila using a context menu item is out of the scope for this project, but maybe in the scope of https://github.com/takluyver/nbopen.

**Comment by 1kastner** [comment]
Thank you very much for the feedback!

**Comment by 1kastner** [comment]
While from https://voila.readthedocs.io/en/stable/using.html it seems possible to open a whole directory, I believe nbopen could be even better since the desired file could be directly accessed. So it is closer to what I want to achieve.
